/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class Ordenarletras extends javax.swing.JFrame {
    int conteo=0;
    DefaultListModel listamodelo = new DefaultListModel();
    DefaultListModel listamodeloOrdenado=new DefaultListModel();
    int error=0;
    /**
     * Creates new form Ordenarletras
     */
    public Ordenarletras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        cmbxopciones = new javax.swing.JComboBox<>();
        btnaccionar = new javax.swing.JToggleButton();
        txtdato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnreiniciar = new javax.swing.JToggleButton();
        btnsalir = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listadatos = new javax.swing.JList<>();
        fondo = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Ordenador alfabetico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        cmbxopciones.setBackground(new java.awt.Color(255, 51, 51));
        cmbxopciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbxopciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar Datos", "Ordenar datos" }));
        cmbxopciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxopcionesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbxopciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        btnaccionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnaccionar.setText("Accionar");
        btnaccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        txtdato.setEditable(false);
        txtdato.setBackground(new java.awt.Color(204, 204, 204));
        txtdato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatoActionPerformed(evt);
            }
        });
        txtdato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdatoKeyPressed(evt);
            }
        });
        getContentPane().add(txtdato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, -1));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dato 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        btnreiniciar.setText("reiniciar");
        btnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnreiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnsalir.setText("salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        listadatos.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(listadatos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 70, 200));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia5/aplicacion2.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatoActionPerformed

    private void btnaccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionarActionPerformed
        if(cmbxopciones.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "debe ingresar 10 datos. Para ingresar el dato escriba la letra y luego presione ENTER");
        txtdato.setEditable(true);
        txtdato.requestFocus();
        btnaccionar.setEnabled(false);
        }else if(cmbxopciones.getSelectedIndex()==1){
        listamodeloOrdenado = listamodelo;
   for(int j=0;j<9;j++){
   for(int iteracion=0;iteracion<9;iteracion++){
   int cast=(int)((this.listamodeloOrdenado.elementAt(iteracion).toString().charAt(0))); 
   int cast2=(int)((this.listamodeloOrdenado.elementAt(iteracion+1).toString().charAt(0)));
   if(cast>cast2){
       Object burbuja = this.listamodeloOrdenado.elementAt(iteracion);
   this.listamodeloOrdenado.setElementAt(this.listamodeloOrdenado.elementAt(iteracion+1), iteracion);
   this.listamodeloOrdenado.setElementAt(burbuja, (iteracion+1));
   }
   }}listadatos.setModel(listamodeloOrdenado);
            }
    }//GEN-LAST:event_btnaccionarActionPerformed

    private void txtdatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyPressed
        int car=(int)evt.getKeyChar();
        if(car>=32 && car<=64){
            JOptionPane.showMessageDialog(null, "solo letra");
            txtdato.setText(null);
        }else if(txtdato.getText().length()==1){
         if(listamodelo.size()<10){
           listamodelo.addElement(txtdato.getText());                  
           listadatos.setModel(listamodelo);
           txtdato.setText(null);
         }else{
             txtdato.setEditable(false);
         }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatoKeyPressed

    private void btnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreiniciarActionPerformed
        txtdato.setText(null);
        listamodelo.clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreiniciarActionPerformed

    private void cmbxopcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxopcionesActionPerformed
    if(cmbxopciones.getSelectedIndex()==1 && listamodelo.getSize()<10){
       JOptionPane.showMessageDialog(null, "debe haber ingresado todos los datos en total son 10");
        btnaccionar.setEnabled(false);
    }else{btnaccionar.setEnabled(true);}
    // TODO add your handling code here:
    }//GEN-LAST:event_cmbxopcionesActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
this.setEnabled(false);
       frmfuncion fun = new frmfuncion();
       fun.show();
       fun.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenarletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenarletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenarletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenarletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenarletras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnaccionar;
    private javax.swing.JToggleButton btnreiniciar;
    private javax.swing.JToggleButton btnsalir;
    private javax.swing.JComboBox<String> cmbxopciones;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listadatos;
    private javax.swing.JTextField txtdato;
    // End of variables declaration//GEN-END:variables
}
